import type { CharacterClass, Subclass } from "../rules.schema";

export const classes = [
  {
    id: "knight",
    name: "Knight",
    description: "A frontline Force-user blending saber combat and Force techniques.",
    hitDie: "d10",
    subclassIds: ["guardian", "sentinel", "vanguard"],
    featureIds: ["force-channel", "lightsaber-defence", "knight-force-casting"],
    startingGearIds: [
      "shock-baton",
      "knight-robes",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "consular",
    name: "Consular",
    description: "A Force-user focused on spiritual depth, diplomacy, and mastery.",
    hitDie: "d6",
    subclassIds: ["sage", "deacon", "shadow"],
    featureIds: ["force-adept", "saber-mastery", "consular-force-casting"],
    startingGearIds: [
      "shock-baton",
      "consular-robes",
      "datapad",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "trooper",
    name: "Trooper",
    description: "A hardened soldier trained for armor, rifles, and battlefield hardware.",
    hitDie: "d10",
    subclassIds: [],
    featureIds: ["combat-drills", "heavy-weapons-training", "tech-specialist"],
    startingGearIds: [
      "sporting-carbine",
      "vibroknife",
      "light-trooper-armor",
      "micro-binoculars",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "scoundrel",
    name: "Scoundrel",
    description: "A quick, lucky operator built around pistols, tricks, and tech.",
    hitDie: "d8",
    subclassIds: [],
    featureIds: ["quick-draw", "gunslinger", "tech-trickster", "uncanny-luck"],
    startingGearIds: [
      "blaster-pistol",
      "vibroknife",
      "scoundrel-vest",
      "basic-id-scrambler",
      "grapnel-launcher",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "bounty-hunter",
    name: "Bounty Hunter",
    description: "A relentless tracker with weapons, armor, gadgets, and contracts.",
    hitDie: "d10",
    subclassIds: [],
    featureIds: ["hunters-arsenal", "predator-shot", "tech-upgrades", "jet-pack"],
    startingGearIds: [
      "hunting-carbine",
      "blaster-pistol",
      "scout-recon-armor",
      "tracking-fob-basic",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "agent",
    name: "Agent",
    description: "A covert specialist focused on stealth, slicing, and precision fire.",
    hitDie: "d6",
    subclassIds: [],
    featureIds: ["infiltrator", "precision-fire", "spycraft", "operative-training", "sniper"],
    startingGearIds: [
      "holdout-blaster",
      "vibroknife",
      "stealth-suit",
      "basic-slicing-rig",
      "optic-scanner",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
] satisfies CharacterClass[];

export const subclasses = [
  {
    id: "guardian",
    classId: "knight",
    name: "Guardian",
    description: "A defensive Knight trained to protect allies and hold the line.",
    featureIds: ["defensive-mastery", "soresu-form"],
  },
  {
    id: "sentinel",
    classId: "knight",
    name: "Sentinel",
    description: "A Knight who blends saber technique with coordinated strikes.",
    featureIds: ["niman-form", "allied-combat"],
  },
  {
    id: "vanguard",
    classId: "knight",
    name: "Vanguard",
    description: "An aggressive Knight focused on powerful saber attacks.",
    featureIds: ["ataru-form", "reckless"],
  },
  {
    id: "sage",
    classId: "consular",
    name: "Sage",
    description: "A mystic Consular specializing in deep Force mastery.",
    featureIds: ["force-savant", "shii-cho-form"],
  },
  {
    id: "deacon",
    classId: "consular",
    name: "Deacon",
    description: "An agile Consular who channels the Force into movement.",
    featureIds: ["shien-form", "force-agility"],
  },
  {
    id: "shadow",
    classId: "consular",
    name: "Shadow",
    description: "A stealth-focused Consular with dangerous saber techniques.",
    featureIds: ["double-blade-mastery", "juyo-form"],
  },
] satisfies Subclass[];
