import type { CharacterClass, Subclass } from "../rules.schema";

export const classes = [
  {
    id: "knight",
    name: "Knight",
    description: "A frontline Force-user blending saber combat and Force techniques.",
    hitDie: "d10",
    subclassIds: ["guardian", "sentinel", "vanguard"],
    featureIds: ["force-channel", "lightsaber-defence", "knight-force-casting"],
    powerSource: "force",
    castingAbility: "wis",
    knownPowerProgression: "knight",
    requiresForcePointToCast: false,
    weaponProficiencyTags: ["lightsabers", "vibroswords", "light"],
    armorProficiencyCategories: ["light"],
    startingGearIds: [
      "shock-baton",
      "knight-robes",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "consular",
    name: "Consular",
    description: "A Force-user focused on spiritual depth, diplomacy, and mastery.",
    hitDie: "d6",
    subclassIds: ["sage", "deacon", "shadow"],
    featureIds: ["force-adept", "saber-mastery", "consular-force-casting"],
    powerSource: "force",
    castingAbility: "int",
    knownPowerProgression: "priest",
    requiresForcePointToCast: false,
    weaponProficiencyTags: ["lightsabers", "staves", "light"],
    armorProficiencyCategories: ["none"],
    startingGearIds: [
      "shock-baton",
      "consular-robes",
      "datapad",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "trooper",
    name: "Trooper",
    description: "A hardened soldier trained for armor, rifles, and battlefield hardware.",
    imagePath: "/images/ruleset/classes/trooper.png",
    hitDie: "d10",
    subclassIds: [],
    featureIds: ["combat-drills", "heavy-weapons-training", "tech-specialist"],
    powerSource: "tech",
    castingAbility: "con",
    knownPowerProgression: "half-level",
    requiresForcePointToCast: true,
    weaponProficiencyTags: [
      "light",
      "rifles",
      "carbines",
      "pistols",
      "knives",
      "vibroswords",
      "heavy-weapons",
      "explosives",
    ],
    armorProficiencyCategories: ["light", "medium", "heavy"],
    startingGearIds: [
      "sporting-carbine",
      "vibroknife",
      "light-trooper-armor",
      "micro-binoculars",
      "medpac",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "scoundrel",
    name: "Scoundrel",
    description: "A quick, lucky operator built around pistols, tricks, and tech.",
    imagePath: "/images/ruleset/classes/scoundrel.png",
    hitDie: "d8",
    subclassIds: [],
    featureIds: ["quick-draw", "gunslinger", "tech-trickster", "uncanny-luck"],
    powerSource: "tech",
    castingAbility: "cha",
    knownPowerProgression: "half-level",
    requiresForcePointToCast: true,
    weaponProficiencyTags: ["light", "pistols", "carbines", "knives", "tech"],
    armorProficiencyCategories: ["light", "tech"],
    startingGearIds: [
      "blaster-pistol",
      "vibroknife",
      "scoundrel-vest",
      "basic-id-scrambler",
      "grapnel-launcher",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "bounty-hunter",
    name: "Bounty Hunter",
    description: "A relentless tracker with weapons, armor, gadgets, and contracts.",
    imagePath: "/images/ruleset/classes/bounty-hunter.png",
    hitDie: "d10",
    subclassIds: [],
    featureIds: ["hunters-arsenal", "predator-shot", "tech-upgrades", "jet-pack"],
    powerSource: "tech",
    castingAbility: "wis",
    knownPowerProgression: "half-level",
    requiresForcePointToCast: true,
    weaponProficiencyTags: [
      "light",
      "rifles",
      "pistols",
      "knives",
      "vibroswords",
      "heavy-weapons",
    ],
    armorProficiencyCategories: ["medium", "heavy"],
    startingGearIds: [
      "hunting-carbine",
      "blaster-pistol",
      "scout-recon-armor",
      "tracking-fob-basic",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
  {
    id: "agent",
    name: "Agent",
    description: "A covert specialist focused on stealth, slicing, and precision fire.",
    imagePath: "/images/ruleset/classes/agent.png",
    hitDie: "d6",
    subclassIds: [],
    featureIds: ["infiltrator", "precision-fire", "spycraft", "operative-training", "sniper"],
    powerSource: "tech",
    castingAbility: "int",
    knownPowerProgression: "half-level",
    requiresForcePointToCast: true,
    weaponProficiencyTags: ["light", "pistols", "knives", "carbines", "explosives", "tech"],
    armorProficiencyCategories: ["tech"],
    startingGearIds: [
      "holdout-blaster",
      "vibroknife",
      "stealth-suit",
      "basic-slicing-rig",
      "optic-scanner",
      "commlink",
      "glowrod",
      "rations-3-days",
      "water-canister",
    ],
  },
] satisfies CharacterClass[];

export const subclasses = [
  {
    id: "guardian",
    classId: "knight",
    name: "Guardian",
    description: "A defensive Knight trained to protect allies and hold the line.",
    imagePath: "/images/ruleset/subclasses/knight-guardian.png",
    featureIds: ["defensive-mastery", "soresu-form"],
    knownPowerBonusAtLevel1: 0,
  },
  {
    id: "sentinel",
    classId: "knight",
    name: "Sentinel",
    description: "A Knight who blends saber technique with coordinated strikes.",
    imagePath: "/images/ruleset/subclasses/knight-sentinel.png",
    featureIds: ["niman-form", "allied-combat"],
    knownPowerBonusAtLevel1: 0,
  },
  {
    id: "vanguard",
    classId: "knight",
    name: "Vanguard",
    description: "An aggressive Knight focused on powerful saber attacks.",
    imagePath: "/images/ruleset/subclasses/knight-vanguard.png",
    featureIds: ["ataru-form", "reckless"],
    knownPowerBonusAtLevel1: 0,
  },
  {
    id: "sage",
    classId: "consular",
    name: "Sage",
    description: "A mystic Consular specializing in deep Force mastery.",
    imagePath: "/images/ruleset/subclasses/consular-sage.png",
    featureIds: ["force-savant", "shii-cho-form"],
    knownPowerBonusAtLevel1: 1,
  },
  {
    id: "deacon",
    classId: "consular",
    name: "Deacon",
    description: "An agile Consular who channels the Force into movement.",
    imagePath: "/images/ruleset/subclasses/consular-deacon.png",
    featureIds: ["shien-form", "force-agility"],
    knownPowerBonusAtLevel1: 0,
  },
  {
    id: "shadow",
    classId: "consular",
    name: "Shadow",
    description: "A stealth-focused Consular with dangerous saber techniques.",
    imagePath: "/images/ruleset/subclasses/consular-shadow.png",
    featureIds: ["double-blade-mastery", "juyo-form"],
    knownPowerBonusAtLevel1: 0,
  },
] satisfies Subclass[];
