import type { Feature } from "../rules.schema";

function customFeature(
  id: string,
  name: string,
  kind: Feature["kind"],
  description = `${name} rule text placeholder.`,
): Feature {
  return {
    id,
    name,
    kind,
    description,
    effects: [{ type: "customText", text: description }],
  };
}

export const features = [
  customFeature("adaptive", "Adaptive", "species"),
  customFeature("bold-opportunist", "Bold Opportunist", "species"),
  customFeature("disciplined-strike", "Disciplined Strike", "species"),
  customFeature("frontier-toughness", "Frontier Toughness", "species"),
  customFeature("way-of-the-warrior", "Way of the Warrior", "species"),
  customFeature("mechanical-body", "Mechanical Body", "species"),
  customFeature("assassin-protocols", "Assassin Protocols", "species"),
  customFeature("cultural-database", "Cultural Database", "species"),
  customFeature("reinforced-chassis", "Reinforced Chassis", "species"),
  customFeature("lekku-awareness", "Lekku Awareness", "species"),
  customFeature("adaptable-physique", "Adaptable Physique", "species"),
  customFeature("rage-of-kashyyyk", "Rage of Kashyyyk", "species"),
  customFeature("thick-hide", "Thick Hide", "species"),
  customFeature("hunters-instincts", "Hunter's Instincts", "species"),
  customFeature("shoot-first", "Shoot First", "species"),
  customFeature("iron-will-endurance", "Iron Will & Endurance", "species"),
  customFeature("montral-echo-sense", "Montral Echo-Sense", "species"),
  customFeature("focused-senses", "Focused Senses", "species"),
  customFeature("voidborn-navigator", "Voidborn Navigator", "species"),
  customFeature("durosian-handling", "Durosian Handling", "species"),

  customFeature("force-channel", "Force Channel", "class"),
  customFeature("lightsaber-defence", "Lightsaber Defence", "class"),
  customFeature("knight-force-casting", "The Force", "class"),
  customFeature("force-adept", "Force Adept", "class"),
  customFeature("saber-mastery", "Saber Mastery", "class"),
  customFeature("consular-force-casting", "The Force", "class"),
  customFeature("combat-drills", "Combat Drills", "class"),
  customFeature("heavy-weapons-training", "Heavy Weapons Training", "class"),
  customFeature("tech-specialist", "Tech Specialist", "class"),
  customFeature("quick-draw", "Quick Draw", "class"),
  customFeature("gunslinger", "Gunslinger", "class"),
  customFeature("tech-trickster", "Tech Trickster", "class"),
  customFeature("uncanny-luck", "Uncanny Luck", "class"),
  customFeature("hunters-arsenal", "Hunter's Arsenal", "class"),
  customFeature("predator-shot", "Predator Shot", "class"),
  customFeature("tech-upgrades", "Tech Upgrades", "class"),
  customFeature("jet-pack", "Jet Pack", "class"),
  customFeature("infiltrator", "Infiltrator", "class"),
  customFeature("precision-fire", "Precision Fire", "class"),
  customFeature("spycraft", "Spycraft", "class"),
  customFeature("operative-training", "Operative Training", "class"),
  customFeature("sniper", "Sniper", "class"),

  customFeature("defensive-mastery", "Defensive Mastery", "subclass"),
  customFeature("soresu-form", "Soresu (Form III)", "subclass"),
  customFeature("niman-form", "Niman (Form VI)", "subclass"),
  customFeature("allied-combat", "Allied Combat", "subclass"),
  customFeature("ataru-form", "Ataru (Form IV)", "subclass"),
  customFeature("reckless", "Reckless", "subclass"),
  customFeature("force-savant", "Force Savant", "subclass"),
  customFeature("shii-cho-form", "Shii-Cho (Form I)", "subclass"),
  customFeature("shien-form", "Shien (Form V)", "subclass"),
  customFeature("force-agility", "Force Agility", "subclass"),
  customFeature("double-blade-mastery", "Double-Blade Mastery", "subclass"),
  customFeature("juyo-form", "Juyo (Form VII)", "subclass"),

  customFeature("outer-rim-farmer-background-feature", "Outer Rim Farmer Talent", "background"),
  customFeature("republic-dropout-background-feature", "Republic Dropout Talent", "background"),
  customFeature("jedi-service-youngling-background-feature", "Jedi Service Youngling Talent", "background"),
  customFeature("lost-temple-survivor-background-feature", "Lost Temple Survivor Talent", "background"),
  customFeature("hidden-force-sensitive-background-feature", "Hidden Force-Sensitive Talent", "background"),
  customFeature("cantina-performer-background-feature", "Cantina Performer Talent", "background"),
  customFeature("scrap-technician-background-feature", "Scrap Technician Talent", "background"),
  customFeature("street-urchin-background-feature", "Street Urchin Talent", "background"),
  customFeature("hutt-enforcer-background-feature", "Hutt Enforcer Talent", "background"),
  customFeature("sith-acolyte-exiled-background-feature", "Sith Acolyte Talent", "background"),
  customFeature("imperial-agent-field-ops-background-feature", "Imperial Agent Talent", "background"),
  customFeature("smuggler-crew-background-feature", "Smuggler Crew Talent", "background"),
  customFeature("republic-military-lifer-background-feature", "Republic Military Lifer Talent", "background"),
  customFeature("mandalorian-foundling-background-feature", "Mandalorian Foundling Talent", "background"),
  customFeature("wilderness-scout-background-feature", "Wilderness Scout Talent", "background"),
  customFeature("droid-programmer-background-feature", "Droid Programmer Talent", "background"),
  customFeature("imperial-defector-background-feature", "Imperial Defector Talent", "background"),
  customFeature("war-refugee-background-feature", "War Refugee Talent", "background"),
  customFeature("true-sith-hidden-background-feature", "True Sith Talent", "background"),
  customFeature("black-market-trader-background-feature", "Black-Market Trader Talent", "background"),
] satisfies Feature[];
