import type { ForcePower } from "../rules.schema";

type PowerSeed = Omit<ForcePower, "description" | "featureIds"> & {
  description?: string;
  featureIds?: string[];
} extends infer Base
  ? Omit<Base, "excluded"> & { excluded?: boolean }
  : never;

const customStarWarsPowers: PowerSeed[] = [
  {
    id: "force-push",
    name: "Force Push",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["telekinetic"],
  },
  {
    id: "force-pull",
    name: "Force Pull",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["telekinetic"],
  },
  {
    id: "force-speed",
    name: "Force Speed",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["movement"],
  },
  {
    id: "force-jump",
    name: "Force Jump",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["movement"],
  },
  {
    id: "telekinesis",
    name: "Telekinesis",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["telekinetic"],
  },
  {
    id: "mind-trick",
    name: "Mind Trick",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["mental"],
  },
  {
    id: "force-lightning",
    name: "Force Lightning",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 3,
    tags: ["dark-side", "damage"],
  },
  {
    id: "force-choke",
    name: "Force Choke",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 4,
    tags: ["dark-side", "telekinetic"],
  },
  {
    id: "lightsaber-throw",
    name: "Lightsaber Throw",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 5,
    tags: ["lightsaber", "telekinetic"],
  },
];

const derivedForcePowers: PowerSeed[] = [
  derivedPower({
    id: "force-vigil",
    name: "Force Vigil",
    kind: "force",
    derivedFromSpellId: "alarm",
    derivedFromSpellName: "Alarm",
    range: "Near",
    duration: "1 hour",
    mechanics: "Sense and alert the caster when a watched area is crossed.",
    tags: ["sense", "ward"],
  }),
  derivedPower({
    id: "force-sense",
    name: "Force Sense",
    kind: "force",
    derivedFromSpellId: "detect-magic",
    derivedFromSpellName: "Detect Magic",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Sense nearby supernatural energy, active powers, and unusual artifacts.",
    tags: ["sense"],
  }),
  derivedPower({
    id: "force-glow",
    name: "Force Glow",
    kind: "force",
    derivedFromSpellId: "light",
    derivedFromSpellName: "Light",
    range: "Near",
    duration: "1 hour",
    mechanics: "Cause a touched or nearby object to shine with useful light.",
    tags: ["utility", "light"],
  }),
  derivedPower({
    id: "force-ward",
    name: "Force Ward",
    kind: "force",
    derivedFromSpellId: "mage-armor",
    derivedFromSpellName: "Mage Armor",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Create a protective field that improves defense while maintained.",
    tags: ["defense"],
  }),
  derivedPower({
    id: "force-bolt",
    name: "Force Bolt",
    kind: "force",
    derivedFromSpellId: "magic-missile",
    derivedFromSpellName: "Magic Missile",
    range: "Far",
    duration: "Instant",
    damage: "1d4",
    mechanics: "Strike a visible target with a focused pulse of Force energy.",
    tags: ["damage"],
  }),
  derivedPower({
    id: "force-drift",
    name: "Force Drift",
    kind: "force",
    derivedFromSpellId: "feather-fall",
    derivedFromSpellName: "Feather Fall",
    range: "Near",
    duration: "Instant",
    mechanics: "Slow a fall enough to land safely.",
    tags: ["movement", "reaction"],
  }),
  derivedPower({
    id: "force-platform",
    name: "Force Platform",
    kind: "force",
    derivedFromSpellId: "floating-disk",
    derivedFromSpellName: "Floating Disk",
    range: "Near",
    duration: "1 hour",
    mechanics: "Create a hovering platform that can carry gear or a willing passenger.",
    tags: ["telekinetic", "utility"],
  }),
  derivedPower({
    id: "force-seal",
    name: "Force Seal",
    kind: "force",
    derivedFromSpellId: "hold-portal",
    derivedFromSpellName: "Hold Portal",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Hold a door, hatch, or similar portal closed with pressure.",
    tags: ["telekinetic", "ward"],
  }),
];

const derivedTechPowers: PowerSeed[] = [
  derivedPower({
    id: "perimeter-sensor",
    name: "Perimeter Sensor",
    kind: "tech",
    derivedFromSpellId: "alarm",
    derivedFromSpellName: "Alarm",
    range: "Near",
    duration: "1 hour",
    mechanics: "Deploy a small sensor that alerts the user when a watched area is crossed.",
    tags: ["sensor", "security"],
  }),
  derivedPower({
    id: "sensor-sweep",
    name: "Sensor Sweep",
    kind: "tech",
    derivedFromSpellId: "detect-magic",
    derivedFromSpellName: "Detect Magic",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Scan for unusual energy signatures, active powers, and exotic devices.",
    tags: ["sensor"],
  }),
  derivedPower({
    id: "glowrod-overcharge",
    name: "Glowrod Overcharge",
    kind: "tech",
    derivedFromSpellId: "light",
    derivedFromSpellName: "Light",
    range: "Near",
    duration: "1 hour",
    mechanics: "Overcharge a light source or small device to illuminate the area.",
    tags: ["utility", "light"],
  }),
  derivedPower({
    id: "personal-shield-pulse",
    name: "Personal Shield Pulse",
    kind: "tech",
    derivedFromSpellId: "mage-armor",
    derivedFromSpellName: "Mage Armor",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Project a short-lived defensive shield while maintained.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "micro-missile-salvo",
    name: "Micro-Missile Salvo",
    kind: "tech",
    derivedFromSpellId: "magic-missile",
    derivedFromSpellName: "Magic Missile",
    range: "Far",
    duration: "Instant",
    damage: "1d4",
    mechanics: "Launch a guided micro-munition at a visible target.",
    tags: ["damage", "munition"],
  }),
  derivedPower({
    id: "emergency-repulsor",
    name: "Emergency Repulsor",
    kind: "tech",
    derivedFromSpellId: "feather-fall",
    derivedFromSpellName: "Feather Fall",
    range: "Near",
    duration: "Instant",
    mechanics: "Trigger a repulsor burst to slow a fall.",
    tags: ["movement", "reaction"],
  }),
  derivedPower({
    id: "cargo-hoverdisc",
    name: "Cargo Hoverdisc",
    kind: "tech",
    derivedFromSpellId: "floating-disk",
    derivedFromSpellName: "Floating Disk",
    range: "Near",
    duration: "1 hour",
    mechanics: "Deploy a hoverdisc that carries gear or a willing passenger.",
    tags: ["utility", "repulsor"],
  }),
  derivedPower({
    id: "magnetic-lock",
    name: "Magnetic Lock",
    kind: "tech",
    derivedFromSpellId: "hold-portal",
    derivedFromSpellName: "Hold Portal",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Clamp a door, hatch, or similar portal shut with a magnetic seal.",
    tags: ["security"],
  }),
];

const gmApprovalPowers: PowerSeed[] = [
  derivedPower({
    id: "force-trance",
    name: "Force Trance",
    kind: "force",
    derivedFromSpellId: "sleep",
    derivedFromSpellName: "Sleep",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Overwhelm weak minds and lull them into a brief trance.",
    tags: ["mental"],
  }),
  derivedPower({
    id: "sonic-stunner",
    name: "Sonic Stunner",
    kind: "tech",
    derivedFromSpellId: "sleep",
    derivedFromSpellName: "Sleep",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Emit a tuned pulse that can stun or drop vulnerable targets.",
    tags: ["sonic", "stun"],
  }),
  derivedPower({
    id: "social-override",
    name: "Social Override",
    kind: "tech",
    derivedFromSpellId: "charm-person",
    derivedFromSpellName: "Charm Person",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Use subliminal cues and slicing tricks to sway a humanoid target.",
    tags: ["influence", "slicing"],
  }),
  derivedPower({
    id: "force-barrier",
    name: "Force Barrier",
    kind: "force",
    derivedFromSpellId: "protection-from-evil",
    derivedFromSpellName: "Protection From Evil",
    approval: "gm-approval",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Create a ward against hostile supernatural or corrupted presences.",
    tags: ["defense", "ward"],
  }),
  derivedPower({
    id: "threat-dampener",
    name: "Threat Dampener",
    kind: "tech",
    derivedFromSpellId: "protection-from-evil",
    derivedFromSpellName: "Protection From Evil",
    approval: "gm-approval",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Tune a shield or jammer against a specific hostile signal or entity.",
    tags: ["defense", "shield"],
  }),
];

const excludedPowers: PowerSeed[] = [
  derivedPower({
    id: "excluded-cure-wounds",
    name: "Cure Wounds",
    kind: "force",
    derivedFromSpellId: "cure-wounds",
    derivedFromSpellName: "Cure Wounds",
    excluded: true,
    exclusionReason: "healing",
    mechanics: "Excluded because direct HP restoration is outside this ruleset.",
    tags: ["healing"],
  }),
];

export const forcePowers = [
  ...customStarWarsPowers,
  ...derivedForcePowers,
  ...derivedTechPowers,
  ...gmApprovalPowers,
  ...excludedPowers,
].map((power) => ({
  ...power,
  excluded: power.excluded ?? false,
  description:
    power.description ??
    `${power.name} ${
      power.source === "shadowdark-derived"
        ? `adapted from ${power.derivedFromSpellName}.`
        : "from the Star Wars Shadowdark homebrew powers list."
    }`,
  featureIds: power.featureIds ?? [],
})) satisfies ForcePower[];

function derivedPower(
  power: Omit<
    PowerSeed,
    "approval" | "availability" | "excluded" | "source" | "tier"
  > & {
    approval?: PowerSeed["approval"];
    excluded?: PowerSeed["excluded"];
    tier?: PowerSeed["tier"];
  },
): PowerSeed {
  return {
    ...power,
    source: "shadowdark-derived",
    availability: [power.kind],
    approval: power.approval ?? "allowed",
    excluded: power.excluded ?? false,
    tier: power.tier ?? 1,
  };
}
