import type { ForcePower } from "../rules.schema";

type PowerSeed = Omit<ForcePower, "description" | "featureIds"> & {
  description?: string;
  featureIds?: string[];
} extends infer Base
  ? Omit<Base, "excluded"> & { excluded?: boolean }
  : never;

const customStarWarsPowers: PowerSeed[] = [
  {
    id: "force-push",
    name: "Force Push",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["telekinetic"],
  },
  {
    id: "force-pull",
    name: "Force Pull",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["telekinetic"],
  },
  {
    id: "force-speed",
    name: "Force Speed",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 1,
    tags: ["movement"],
  },
  {
    id: "force-jump",
    name: "Force Jump",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["movement"],
  },
  {
    id: "telekinesis",
    name: "Telekinesis",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["telekinetic"],
  },
  {
    id: "mind-trick",
    name: "Mind Trick",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 2,
    tags: ["mental"],
  },
  {
    id: "force-lightning",
    name: "Force Lightning",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 3,
    tags: ["dark-side", "damage"],
  },
  {
    id: "force-choke",
    name: "Force Choke",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 4,
    tags: ["dark-side", "telekinetic"],
  },
  {
    id: "lightsaber-throw",
    name: "Lightsaber Throw",
    kind: "force",
    source: "star-wars-homebrew",
    availability: ["force"],
    approval: "allowed",
    tier: 5,
    tags: ["lightsaber", "telekinetic"],
  },
];

const derivedForcePowers: PowerSeed[] = [
  derivedPower({
    id: "force-vigil",
    name: "Force Vigil",
    kind: "force",
    derivedFromSpellId: "alarm",
    derivedFromSpellName: "Alarm",
    range: "Near",
    duration: "1 hour",
    mechanics: "Sense and alert the caster when a watched area is crossed.",
    tags: ["sense", "ward"],
  }),
  derivedPower({
    id: "force-sense",
    name: "Force Sense",
    kind: "force",
    derivedFromSpellId: "detect-magic",
    derivedFromSpellName: "Detect Magic",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Sense nearby supernatural energy, active powers, and unusual artifacts.",
    tags: ["sense"],
  }),
  derivedPower({
    id: "thermal-burst",
    name: "Thermal Burst",
    kind: "force",
    derivedFromSpellId: "burning-hands",
    derivedFromSpellName: "Burning Hands",
    range: "Close",
    duration: "Instant",
    damage: "1d6",
    mechanics:
      "Unleash a burst of heat in a close area; creatures in the area take damage and flammable objects ignite. On a failed casting check, the power is lost until rest.",
    tags: ["damage", "fire", "area"],
  }),
  derivedPower({
    id: "force-glow",
    name: "Force Glow",
    kind: "force",
    derivedFromSpellId: "light",
    derivedFromSpellName: "Light",
    range: "Near",
    duration: "1 hour",
    mechanics: "Cause a touched or nearby object to shine with useful light.",
    tags: ["utility", "light"],
  }),
  derivedPower({
    id: "force-ward",
    name: "Force Ward",
    kind: "force",
    derivedFromSpellId: "mage-armor",
    derivedFromSpellName: "Mage Armor",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Create a protective field that improves defense while maintained.",
    tags: ["defense"],
  }),
  derivedPower({
    id: "force-bolt",
    name: "Force Bolt",
    kind: "force",
    derivedFromSpellId: "magic-missile",
    derivedFromSpellName: "Magic Missile",
    range: "Far",
    duration: "Instant",
    damage: "1d4",
    mechanics: "Strike a visible target with a focused pulse of Force energy.",
    tags: ["damage"],
  }),
  derivedPower({
    id: "force-imbue",
    name: "Force Imbue",
    kind: "force",
    derivedFromSpellId: "holy-weapon",
    derivedFromSpellName: "Holy Weapon",
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Enhance a weapon with Force energy, granting +1 to attack and damage rolls.",
    tags: ["weapon", "enhancement", "supportive"],
  }),
  derivedPower({
    id: "force-drift",
    name: "Force Drift",
    kind: "force",
    derivedFromSpellId: "feather-fall",
    derivedFromSpellName: "Feather Fall",
    range: "Near",
    duration: "Instant",
    mechanics: "Slow a fall enough to land safely.",
    tags: ["movement", "reaction"],
  }),
  derivedPower({
    id: "force-platform",
    name: "Force Platform",
    kind: "force",
    derivedFromSpellId: "floating-disk",
    derivedFromSpellName: "Floating Disk",
    range: "Near",
    duration: "1 hour",
    mechanics: "Create a hovering platform that can carry gear or a willing passenger.",
    tags: ["telekinetic", "utility"],
  }),
  derivedPower({
    id: "force-seal",
    name: "Force Seal",
    kind: "force",
    derivedFromSpellId: "hold-portal",
    derivedFromSpellName: "Hold Portal",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Hold a door, hatch, or similar portal closed with pressure.",
    tags: ["telekinetic", "ward"],
  }),
  derivedPower({
    id: "force-premonition",
    name: "Force Premonition",
    kind: "force",
    derivedFromSpellId: "augury",
    derivedFromSpellName: "Augury",
    tier: 2,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Read omens around a specific course of action; the GM indicates whether it points toward weal or woe.",
    tags: ["sense", "divination"],
  }),
  derivedPower({
    id: "corrosive-force-bolt",
    name: "Corrosive Force Bolt",
    kind: "force",
    derivedFromSpellId: "acid-arrow",
    derivedFromSpellName: "Acid Arrow",
    tier: 2,
    range: "Far",
    duration: "Focus",
    focus: true,
    damage: "1d6/round",
    mechanics:
      "Lodge a corrosive Force bolt in one foe, dealing damage each round while focus is maintained.",
    tags: ["damage", "corrosive"],
  }),
  derivedPower({
    id: "force-shapeshift",
    name: "Force Shapeshift",
    kind: "force",
    derivedFromSpellId: "alter-self",
    derivedFromSpellName: "Alter Self",
    tier: 2,
    range: "Self",
    duration: "5 rounds",
    mechanics:
      "Alter your physical form with one natural feature, such as gills or claws, without growing wings or extra limbs.",
    tags: ["transformation", "utility"],
  }),
  derivedPower({
    id: "mind-probe",
    name: "Mind Probe",
    kind: "force",
    derivedFromSpellId: "detect-thoughts",
    derivedFromSpellName: "Detect Thoughts",
    tier: 2,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Read the immediate thoughts of one visible creature; it can notice and end the intrusion with a Wisdom check.",
    tags: ["mental", "sense"],
  }),
  derivedPower({
    id: "force-anchor",
    name: "Force Anchor",
    kind: "force",
    derivedFromSpellId: "fixed-object",
    derivedFromSpellName: "Fixed Object",
    tier: 2,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Fix a small touched object in place so it can support tremendous weight for the duration.",
    tags: ["telekinetic", "utility"],
  }),
  derivedPower({
    id: "force-stasis",
    name: "Force Stasis",
    kind: "force",
    derivedFromSpellId: "hold-person",
    derivedFromSpellName: "Hold Person",
    tier: 2,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Paralyze one visible humanoid of LV 4 or less while focus is maintained.",
    tags: ["control", "mental"],
  }),
  derivedPower({
    id: "force-veil",
    name: "Force Veil",
    kind: "force",
    derivedFromSpellId: "invisibility",
    derivedFromSpellName: "Invisibility",
    tier: 2,
    range: "Close",
    duration: "10 rounds",
    mechanics:
      "Turn a touched creature invisible until the duration ends or it attacks or casts.",
    tags: ["stealth", "utility"],
  }),
  derivedPower({
    id: "force-breach",
    name: "Force Breach",
    kind: "force",
    derivedFromSpellId: "knock",
    derivedFromSpellName: "Knock",
    tier: 2,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Force open a visible door, portal, chest, window, or gate, defeating mundane locks with an audible report.",
    tags: ["telekinetic", "utility"],
  }),
  derivedPower({
    id: "force-lift",
    name: "Force Lift",
    kind: "force",
    derivedFromSpellId: "levitate",
    derivedFromSpellName: "Levitate",
    tier: 2,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Float vertically a near distance each round and push from solid objects to move horizontally.",
    tags: ["movement", "telekinetic"],
  }),
  derivedPower({
    id: "force-echoes",
    name: "Force Echoes",
    kind: "force",
    derivedFromSpellId: "mirror-image",
    derivedFromSpellName: "Mirror Image",
    tier: 2,
    range: "Self",
    duration: "5 rounds",
    mechanics:
      "Create illusory duplicates that mimic you and absorb incoming attacks until depleted.",
    tags: ["illusion", "defense"],
  }),
  derivedPower({
    id: "force-blink",
    name: "Force Blink",
    kind: "force",
    derivedFromSpellId: "misty-step",
    derivedFromSpellName: "Misty Step",
    tier: 2,
    range: "Self",
    duration: "Instant",
    mechanics: "Teleport a near distance to a visible location.",
    tags: ["movement", "travel"],
  }),
  derivedPower({
    id: "null-presence",
    name: "Null Presence",
    kind: "force",
    derivedFromSpellId: "silence",
    derivedFromSpellName: "Silence",
    tier: 2,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Mute sound in a near-sized cube within range; creatures inside are deafened and cannot be heard.",
    tags: ["control", "utility"],
  }),
  derivedPower({
    id: "force-snare",
    name: "Force Snare",
    kind: "force",
    derivedFromSpellId: "web",
    derivedFromSpellName: "Web",
    tier: 2,
    range: "Far",
    duration: "5 rounds",
    mechanics:
      "Create a near-sized snare field that immobilizes creatures until they win a Strength check.",
    tags: ["control", "area"],
  }),
  derivedPower({
    id: "dominating-word",
    name: "Dominating Word",
    kind: "force",
    derivedFromSpellId: "command",
    derivedFromSpellName: "Command",
    tier: 3,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Issue a one-word command to a creature that understands you; harmful commands allow a Charisma check to end the effect.",
    tags: ["mental", "control"],
  }),
  derivedPower({
    id: "spirit-release",
    name: "Spirit Release",
    kind: "force",
    derivedFromSpellId: "lay-to-rest",
    derivedFromSpellName: "Lay to Rest",
    tier: 3,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Destroy a touched undead creature of LV 9 or less, sending it fully into the afterlife.",
    tags: ["anti-undead", "control"],
  }),
  derivedPower({
    id: "force-repulsion",
    name: "Force Repulsion",
    kind: "force",
    derivedFromSpellId: "rebuke-unholy",
    derivedFromSpellName: "Rebuke Unholy",
    tier: 3,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Force opposed supernatural beings within near to flee for 5 rounds; weak targets that fail badly may be destroyed.",
    tags: ["control", "ward"],
  }),
  derivedPower({
    id: "echoes-of-the-force",
    name: "Echoes of the Force",
    kind: "force",
    derivedFromSpellId: "speak-with-dead",
    derivedFromSpellName: "Speak With Dead",
    tier: 3,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Touch a corpse and ask up to three yes-or-no questions answered by lingering echoes.",
    tags: ["sense", "communication"],
  }),
  derivedPower({
    id: "force-disruption",
    name: "Force Disruption",
    kind: "force",
    derivedFromSpellId: "dispel-magic",
    derivedFromSpellName: "Dispel Magic",
    tier: 3,
    range: "Near",
    duration: "Instant",
    mechanics: "End one active power or spell affecting a visible target in range.",
    tags: ["utility", "counter"],
  }),
  derivedPower({
    id: "force-construct",
    name: "Force Construct",
    kind: "force",
    derivedFromSpellId: "fabricate",
    derivedFromSpellName: "Fabricate",
    tier: 3,
    range: "Near",
    duration: "10 rounds",
    mechanics:
      "Shape raw, nonliving materials up to tree-sized scale into a finished work that reverts when the duration ends.",
    tags: ["utility", "creation"],
  }),
  derivedPower({
    id: "force-detonation",
    name: "Force Detonation",
    kind: "force",
    derivedFromSpellId: "fireball",
    derivedFromSpellName: "Fireball",
    tier: 3,
    range: "Far",
    duration: "Instant",
    damage: "4d6",
    mechanics:
      "Launch a compact Force charge that detonates in a near-sized cube, damaging all creatures in the area.",
    tags: ["damage", "area"],
  }),
  derivedPower({
    id: "force-glide",
    name: "Force Glide",
    kind: "force",
    derivedFromSpellId: "fly",
    derivedFromSpellName: "Fly",
    tier: 3,
    range: "Self",
    duration: "5 rounds",
    mechanics: "Fly near each round and hover in place for the duration.",
    tags: ["movement"],
  }),
  derivedPower({
    id: "force-dissolution",
    name: "Force Dissolution",
    kind: "force",
    derivedFromSpellId: "gaseous-form",
    derivedFromSpellName: "Gaseous Form",
    tier: 3,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Turn yourself and carried gear into vapor, allowing flight through smoke-sized gaps while sensing nearby terrain and movement.",
    tags: ["transformation", "movement"],
  }),
  derivedPower({
    id: "force-illusion",
    name: "Force Illusion",
    kind: "force",
    derivedFromSpellId: "illusion",
    derivedFromSpellName: "Illusion",
    tier: 3,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Create a convincing visible and audible illusion filling up to a near-sized cube; inspection can reveal the falsehood.",
    tags: ["illusion", "utility"],
  }),
  derivedPower({
    id: "force-surge",
    name: "Force Surge",
    kind: "force",
    derivedFromSpellId: "lightning-bolt",
    derivedFromSpellName: "Lightning Bolt",
    tier: 3,
    range: "Far",
    duration: "Instant",
    damage: "3d6",
    mechanics:
      "Release a straight-line surge out to far range, damaging all creatures in its path.",
    tags: ["damage", "area"],
  }),
  derivedPower({
    id: "force-barrier-ring",
    name: "Force Barrier Ring",
    kind: "force",
    derivedFromSpellId: "magic-circle",
    derivedFromSpellName: "Magic Circle",
    tier: 3,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Create a protective circle against a named creature type; chosen creatures cannot attack or use hostile powers against those inside.",
    tags: ["defense", "ward"],
  }),
  derivedPower({
    id: "force-resistance",
    name: "Force Resistance",
    kind: "force",
    derivedFromSpellId: "protection-from-energy",
    derivedFromSpellName: "Protection From Energy",
    tier: 3,
    range: "Close",
    duration: "Focus",
    focus: true,
    mechanics:
      "Protect a touched creature from one energy type, making it immune to harm from that energy while maintained.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "force-transmission",
    name: "Force Transmission",
    kind: "force",
    derivedFromSpellId: "sending",
    derivedFromSpellName: "Sending",
    tier: 3,
    range: "Unlimited",
    duration: "Instant",
    mechanics:
      "Send a brief mental message to a familiar creature on the same plane.",
    tags: ["communication", "mental"],
  }),
  derivedPower({
    id: "commune-with-the-force",
    name: "Commune with the Force",
    kind: "force",
    derivedFromSpellId: "commune",
    derivedFromSpellName: "Commune",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Seek guidance through the Force and ask up to three yes-or-no questions answered truthfully.",
    tags: ["sense", "divination"],
  }),
  derivedPower({
    id: "force-flow",
    name: "Force Flow",
    kind: "force",
    derivedFromSpellId: "control-water",
    derivedFromSpellName: "Control Water",
    tier: 4,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Move and shape a large section of water, making it change form, defy gravity, or flow differently.",
    tags: ["control", "utility"],
  }),
  derivedPower({
    id: "force-impact",
    name: "Force Impact",
    kind: "force",
    derivedFromSpellId: "flame-strike",
    derivedFromSpellName: "Flame Strike",
    tier: 4,
    range: "Far",
    duration: "Instant",
    damage: "2d6",
    mechanics:
      "Call down a focused Force impact on one visible creature in range.",
    tags: ["damage"],
  }),
  derivedPower({
    id: "force-petrify",
    name: "Force Petrify",
    kind: "force",
    derivedFromSpellId: "pillar-of-salt",
    derivedFromSpellName: "Pillar of Salt",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Begin turning a visible creature of LV 5 or less into a hardened statue; three consecutive focused rounds make it permanent.",
    tags: ["control", "transformation"],
  }),
  derivedPower({
    id: "force-judgment",
    name: "Force Judgment",
    kind: "force",
    derivedFromSpellId: "wrath",
    derivedFromSpellName: "Wrath",
    tier: 4,
    range: "Self",
    duration: "10 rounds",
    damage: "+1d8",
    mechanics:
      "Empower your weapons to become magical +2 and deal an additional d8 damage for the duration.",
    tags: ["weapon", "enhancement", "damage"],
  }),
  derivedPower({
    id: "force-sight-projection",
    name: "Force Sight Projection",
    kind: "force",
    derivedFromSpellId: "arcane-eye",
    derivedFromSpellName: "Arcane Eye",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Project an invisible mobile sensor you can see through; it sees in darkness, flies near each turn, and fits through tiny openings.",
    tags: ["sense", "utility"],
  }),
  derivedPower({
    id: "force-decay-field",
    name: "Force Decay Field",
    kind: "force",
    derivedFromSpellId: "cloudkill",
    derivedFromSpellName: "Cloudkill",
    tier: 4,
    range: "Far",
    duration: "5 rounds",
    damage: "2d6/round",
    mechanics:
      "Fill a near-sized cube with a blinding decay field that damages creatures at the start of their turns; weaker creatures that linger may die.",
    tags: ["damage", "area", "control"],
  }),
  derivedPower({
    id: "mind-fracture",
    name: "Mind Fracture",
    kind: "force",
    derivedFromSpellId: "confusion",
    derivedFromSpellName: "Confusion",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Mesmerize one visible creature so it cannot act and moves randomly; powerful targets can shake it off with Wisdom.",
    tags: ["mental", "control"],
  }),
  derivedPower({
    id: "force-rift",
    name: "Force Rift",
    kind: "force",
    derivedFromSpellId: "dimension-door",
    derivedFromSpellName: "Dimension Door",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Teleport yourself and one willing creature to any visible point.",
    tags: ["travel", "movement"],
  }),
  derivedPower({
    id: "deep-premonition",
    name: "Deep Premonition",
    kind: "force",
    derivedFromSpellId: "divination",
    derivedFromSpellName: "Divination",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Seek a portent and ask the GM one yes-or-no question answered truthfully.",
    tags: ["sense", "divination"],
  }),
  derivedPower({
    id: "phase-through",
    name: "Phase Through",
    kind: "force",
    derivedFromSpellId: "passwall",
    derivedFromSpellName: "Passwall",
    tier: 4,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Open a straight passage through a touched barrier, up to near distance in length.",
    tags: ["travel", "utility"],
  }),
  derivedPower({
    id: "force-transformation",
    name: "Force Transformation",
    kind: "force",
    derivedFromSpellId: "polymorph",
    derivedFromSpellName: "Polymorph",
    tier: 4,
    range: "Close",
    duration: "10 rounds",
    mechanics:
      "Transform a touched creature into a natural creature of equal or smaller size, with limits for unwilling targets.",
    tags: ["transformation", "control"],
  }),
  derivedPower({
    id: "force-bubble",
    name: "Force Bubble",
    kind: "force",
    derivedFromSpellId: "resilient-sphere",
    derivedFromSpellName: "Resilient Sphere",
    tier: 4,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Create a weightless sphere around you that blocks passage and crushing force and can roll a near distance each turn.",
    tags: ["defense", "movement"],
  }),
  derivedPower({
    id: "force-harden",
    name: "Force Harden",
    kind: "force",
    derivedFromSpellId: "stoneskin",
    derivedFromSpellName: "Stoneskin",
    tier: 4,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Harden your body, raising AC to 17 for the duration, or 20 on a critical casting check.",
    tags: ["defense"],
  }),
  derivedPower({
    id: "advanced-telekinesis",
    name: "Advanced Telekinesis",
    kind: "force",
    derivedFromSpellId: "telekinesis",
    derivedFromSpellName: "Telekinesis",
    tier: 4,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Lift and move a creature or object up to 1,000 pounds a near distance each round, or hold it in place.",
    tags: ["telekinetic", "control"],
  }),
  derivedPower({
    id: "force-wall",
    name: "Force Wall",
    kind: "force",
    derivedFromSpellId: "wall-of-force",
    derivedFromSpellName: "Wall of Force",
    tier: 4,
    range: "Near",
    duration: "5 rounds",
    mechanics:
      "Conjure a shaped, transparent wall over a near-sized area that blocks physical passage on the same plane.",
    tags: ["defense", "ward"],
  }),
  derivedPower({
    id: "force-retribution",
    name: "Force Retribution",
    kind: "force",
    derivedFromSpellId: "divine-vengeance",
    derivedFromSpellName: "Divine Vengeance",
    tier: 5,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Become an avatar of retribution: fly near, make weapons magical, and gain +4 to weapon attack and damage rolls.",
    tags: ["movement", "weapon", "enhancement"],
  }),
  derivedPower({
    id: "total-domination",
    name: "Total Domination",
    kind: "force",
    derivedFromSpellId: "dominion",
    derivedFromSpellName: "Dominion",
    tier: 5,
    range: "Near",
    duration: "10 rounds",
    mechanics:
      "Call powerful allied beings with up to 16 combined levels to aid you for the duration.",
    tags: ["summoning", "control"],
  }),
  derivedPower({
    id: "final-judgment",
    name: "Final Judgment",
    kind: "force",
    derivedFromSpellId: "judgment",
    derivedFromSpellName: "Judgment",
    tier: 5,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Banish a touched intelligent creature of LV 10 or less for judgment, returning it altered by that judgment after the duration.",
    tags: ["control", "travel"],
  }),
  derivedPower({
    id: "force-transcendence",
    name: "Force Transcendence",
    kind: "force",
    derivedFromSpellId: "plane-shift",
    derivedFromSpellName: "Plane Shift",
    tier: 5,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Transport yourself and willing creatures within close range to another plane, with uncertainty if the destination is unfamiliar.",
    tags: ["travel"],
  }),
  derivedPower({
    id: "grand-vision",
    name: "Grand Vision",
    kind: "force",
    derivedFromSpellId: "prophecy",
    derivedFromSpellName: "Prophecy",
    tier: 5,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Commune for guidance and ask one question answered truthfully within the limits of the source's knowledge.",
    tags: ["sense", "divination"],
  }),
  derivedPower({
    id: "force-null-field",
    name: "Force Null Field",
    kind: "force",
    derivedFromSpellId: "antimagic-shell",
    derivedFromSpellName: "Antimagic Shell",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Create a near-sized null field centered on you where powers, spells, and magic items have no effect.",
    tags: ["defense", "counter"],
  }),
  derivedPower({
    id: "force-annihilation",
    name: "Force Annihilation",
    kind: "force",
    derivedFromSpellId: "disintegrate",
    derivedFromSpellName: "Disintegrate",
    tier: 5,
    range: "Far",
    duration: "Instant",
    damage: "3d8",
    mechanics:
      "Reduce a creature or object to ash; weak creatures die outright, while stronger creatures take damage.",
    tags: ["damage"],
  }),
  derivedPower({
    id: "greater-stasis",
    name: "Greater Stasis",
    kind: "force",
    derivedFromSpellId: "hold-monster",
    derivedFromSpellName: "Hold Monster",
    tier: 5,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Paralyze one visible creature; powerful targets can attempt a Strength check each turn to end the effect.",
    tags: ["control"],
  }),
  derivedPower({
    id: "death-word",
    name: "Death Word",
    kind: "force",
    derivedFromSpellId: "power-word-kill",
    derivedFromSpellName: "Power Word Kill",
    tier: 5,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Utter a lethal word that kills one target of LV 9 or less that can hear it; failed casting is treated as a critical failure.",
    tags: ["mental", "damage"],
  }),
  derivedPower({
    id: "force-spectrum-burst",
    name: "Force Spectrum Burst",
    kind: "force",
    derivedFromSpellId: "prismatic-orb",
    derivedFromSpellName: "Prismatic Orb",
    tier: 5,
    range: "Far",
    duration: "Instant",
    damage: "3d8",
    mechanics:
      "Launch a concussive burst of chosen energy; targets anathema to that energy take double damage.",
    tags: ["damage", "energy"],
  }),
  derivedPower({
    id: "force-vision",
    name: "Force Vision",
    kind: "force",
    derivedFromSpellId: "scrying",
    derivedFromSpellName: "Scrying",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "View and hear a distant creature or location on the same plane; observed creatures can notice the vision.",
    tags: ["sense", "divination"],
  }),
  derivedPower({
    id: "perfect-transformation",
    name: "Perfect Transformation",
    kind: "force",
    derivedFromSpellId: "shapechange",
    derivedFromSpellName: "Shapechange",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Transform yourself and carried gear into a natural creature you have seen of LV 10 or less while retaining nonphysical stats.",
    tags: ["transformation"],
  }),
  derivedPower({
    id: "force-summoning",
    name: "Force Summoning",
    kind: "force",
    derivedFromSpellId: "summon-extraplanar",
    derivedFromSpellName: "Summon Extraplanar",
    tier: 5,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Summon an elemental or outsider of LV 7 or less under your control; losing focus makes it hostile until returned.",
    tags: ["summoning", "control"],
  }),
  derivedPower({
    id: "force-shift",
    name: "Force Shift",
    kind: "force",
    derivedFromSpellId: "teleport",
    derivedFromSpellName: "Teleport",
    tier: 5,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Teleport yourself and willing creatures within close range to a known same-plane destination, with off-target risk for unfamiliar locations.",
    tags: ["travel"],
  }),
];

const derivedTechPowers: PowerSeed[] = [
  derivedPower({
    id: "perimeter-sensor",
    name: "Perimeter Sensor",
    kind: "tech",
    derivedFromSpellId: "alarm",
    derivedFromSpellName: "Alarm",
    range: "Near",
    duration: "1 hour",
    mechanics: "Deploy a small sensor that alerts the user when a watched area is crossed.",
    tags: ["sensor", "security"],
  }),
  derivedPower({
    id: "sensor-sweep",
    name: "Sensor Sweep",
    kind: "tech",
    derivedFromSpellId: "detect-magic",
    derivedFromSpellName: "Detect Magic",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Scan for unusual energy signatures, active powers, and exotic devices.",
    tags: ["sensor"],
  }),
  derivedPower({
    id: "flame-projector",
    name: "Flame Projector",
    kind: "tech",
    derivedFromSpellId: "burning-hands",
    derivedFromSpellName: "Burning Hands",
    range: "Close",
    duration: "Instant",
    damage: "1d6",
    mechanics:
      "Project a burst of heat in a close area; creatures in the area take damage and flammable objects ignite. On a failed casting check, the power is lost until rest.",
    tags: ["damage", "fire", "area"],
  }),
  derivedPower({
    id: "glowrod-overcharge",
    name: "Glowrod Overcharge",
    kind: "tech",
    derivedFromSpellId: "light",
    derivedFromSpellName: "Light",
    range: "Near",
    duration: "1 hour",
    mechanics: "Overcharge a light source or small device to illuminate the area.",
    tags: ["utility", "light"],
  }),
  derivedPower({
    id: "personal-shield-pulse",
    name: "Personal Shield Pulse",
    kind: "tech",
    derivedFromSpellId: "mage-armor",
    derivedFromSpellName: "Mage Armor",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Project a short-lived defensive shield while maintained.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "micro-missile-salvo",
    name: "Micro-Missile Salvo",
    kind: "tech",
    derivedFromSpellId: "magic-missile",
    derivedFromSpellName: "Magic Missile",
    range: "Far",
    duration: "Instant",
    damage: "1d4",
    mechanics: "Launch a guided micro-munition at a visible target.",
    tags: ["damage", "munition"],
  }),
  derivedPower({
    id: "energized-weapon",
    name: "Energized Weapon",
    kind: "tech",
    derivedFromSpellId: "holy-weapon",
    derivedFromSpellName: "Holy Weapon",
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Energize a weapon, granting +1 to attack and damage rolls.",
    tags: ["weapon", "enhancement", "supportive"],
  }),
  derivedPower({
    id: "emergency-repulsor",
    name: "Emergency Repulsor",
    kind: "tech",
    derivedFromSpellId: "feather-fall",
    derivedFromSpellName: "Feather Fall",
    range: "Near",
    duration: "Instant",
    mechanics: "Trigger a repulsor burst to slow a fall.",
    tags: ["movement", "reaction"],
  }),
  derivedPower({
    id: "cargo-hoverdisc",
    name: "Cargo Hoverdisc",
    kind: "tech",
    derivedFromSpellId: "floating-disk",
    derivedFromSpellName: "Floating Disk",
    range: "Near",
    duration: "1 hour",
    mechanics: "Deploy a hoverdisc that carries gear or a willing passenger.",
    tags: ["utility", "repulsor"],
  }),
  derivedPower({
    id: "magnetic-lock",
    name: "Magnetic Lock",
    kind: "tech",
    derivedFromSpellId: "hold-portal",
    derivedFromSpellName: "Hold Portal",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Clamp a door, hatch, or similar portal shut with a magnetic seal.",
    tags: ["security"],
  }),
  derivedPower({
    id: "personal-shield",
    name: "Personal Shield",
    kind: "tech",
    derivedFromSpellId: "shield-of-faith",
    derivedFromSpellName: "Shield of Faith",
    range: "Close",
    duration: "Focus",
    focus: true,
    mechanics:
      "Project a personal shield around a target, granting +2 AC while maintained.",
    tags: ["defense", "shield", "supportive"],
  }),
  derivedPower({
    id: "predictive-analysis",
    name: "Predictive Analysis",
    kind: "tech",
    derivedFromSpellId: "augury",
    derivedFromSpellName: "Augury",
    tier: 2,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Run predictive models for a specific course of action; the GM indicates whether it points toward weal or woe.",
    tags: ["sensor", "divination"],
  }),
  derivedPower({
    id: "acid-dart-launcher",
    name: "Acid Dart Launcher",
    kind: "tech",
    derivedFromSpellId: "acid-arrow",
    derivedFromSpellName: "Acid Arrow",
    tier: 2,
    range: "Far",
    duration: "Focus",
    focus: true,
    damage: "1d6/round",
    mechanics:
      "Fire a corrosive dart into one foe, dealing damage each round while focus is maintained.",
    tags: ["damage", "corrosive", "munition"],
  }),
  derivedPower({
    id: "adaptive-disguise-matrix",
    name: "Adaptive Disguise Matrix",
    kind: "tech",
    derivedFromSpellId: "alter-self",
    derivedFromSpellName: "Alter Self",
    tier: 2,
    range: "Self",
    duration: "5 rounds",
    mechanics:
      "Reconfigure your appearance with one natural-seeming feature, such as gills or claws, without creating wings or extra limbs.",
    tags: ["transformation", "utility"],
  }),
  derivedPower({
    id: "neural-scanner",
    name: "Neural Scanner",
    kind: "tech",
    derivedFromSpellId: "detect-thoughts",
    derivedFromSpellName: "Detect Thoughts",
    tier: 2,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Scan the immediate thoughts of one visible creature; it can notice and end the scan with a Wisdom check.",
    tags: ["sensor", "mental"],
  }),
  derivedPower({
    id: "magnetic-stabilizer",
    name: "Magnetic Stabilizer",
    kind: "tech",
    derivedFromSpellId: "fixed-object",
    derivedFromSpellName: "Fixed Object",
    tier: 2,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Lock a small touched object in place so it can support tremendous weight for the duration.",
    tags: ["utility", "repulsor"],
  }),
  derivedPower({
    id: "paralysis-field",
    name: "Paralysis Field",
    kind: "tech",
    derivedFromSpellId: "hold-person",
    derivedFromSpellName: "Hold Person",
    tier: 2,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Paralyze one visible humanoid of LV 4 or less while focus is maintained.",
    tags: ["control", "stun"],
  }),
  derivedPower({
    id: "active-cloaking",
    name: "Active Cloaking",
    kind: "tech",
    derivedFromSpellId: "invisibility",
    derivedFromSpellName: "Invisibility",
    tier: 2,
    range: "Close",
    duration: "10 rounds",
    mechanics:
      "Cloak a touched creature until the duration ends or it attacks or casts.",
    tags: ["stealth", "utility"],
  }),
  derivedPower({
    id: "auto-slicer-pulse",
    name: "Auto-Slicer Pulse",
    kind: "tech",
    derivedFromSpellId: "knock",
    derivedFromSpellName: "Knock",
    tier: 2,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Open a visible door, portal, chest, window, or gate, defeating mundane locks with an audible pulse.",
    tags: ["slicing", "utility"],
  }),
  derivedPower({
    id: "repulsor-lift",
    name: "Repulsor Lift",
    kind: "tech",
    derivedFromSpellId: "levitate",
    derivedFromSpellName: "Levitate",
    tier: 2,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Float vertically a near distance each round and push from solid objects to move horizontally.",
    tags: ["movement", "repulsor"],
  }),
  derivedPower({
    id: "holographic-duplicates",
    name: "Holographic Duplicates",
    kind: "tech",
    derivedFromSpellId: "mirror-image",
    derivedFromSpellName: "Mirror Image",
    tier: 2,
    range: "Self",
    duration: "5 rounds",
    mechanics:
      "Project holographic doubles that mimic you and absorb incoming attacks until depleted.",
    tags: ["illusion", "defense", "hologram"],
  }),
  derivedPower({
    id: "short-range-teleport",
    name: "Short-Range Teleport",
    kind: "tech",
    derivedFromSpellId: "misty-step",
    derivedFromSpellName: "Misty Step",
    tier: 2,
    range: "Self",
    duration: "Instant",
    mechanics: "Teleport a near distance to a visible location.",
    tags: ["movement", "travel"],
  }),
  derivedPower({
    id: "sound-dampener-field",
    name: "Sound Dampener Field",
    kind: "tech",
    derivedFromSpellId: "silence",
    derivedFromSpellName: "Silence",
    tier: 2,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Mute sound in a near-sized cube within range; creatures inside are deafened and cannot be heard.",
    tags: ["control", "utility"],
  }),
  derivedPower({
    id: "adhesive-net-launcher",
    name: "Adhesive Net Launcher",
    kind: "tech",
    derivedFromSpellId: "web",
    derivedFromSpellName: "Web",
    tier: 2,
    range: "Far",
    duration: "5 rounds",
    mechanics:
      "Launch a near-sized adhesive net field that immobilizes creatures until they win a Strength check.",
    tags: ["control", "area", "munition"],
  }),
  derivedPower({
    id: "authority-override",
    name: "Authority Override",
    kind: "tech",
    derivedFromSpellId: "command",
    derivedFromSpellName: "Command",
    tier: 3,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Issue a one-word override to a creature that understands you; harmful orders allow a Charisma check to end the effect.",
    tags: ["mental", "control"],
  }),
  derivedPower({
    id: "neural-shutdown-protocol",
    name: "Neural Shutdown Protocol",
    kind: "tech",
    derivedFromSpellId: "lay-to-rest",
    derivedFromSpellName: "Lay to Rest",
    tier: 3,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Permanently shut down a touched undead creature of LV 9 or less.",
    tags: ["anti-undead", "control"],
  }),
  derivedPower({
    id: "anti-entity-pulse",
    name: "Anti-Entity Pulse",
    kind: "tech",
    derivedFromSpellId: "rebuke-unholy",
    derivedFromSpellName: "Rebuke Unholy",
    tier: 3,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Pulse opposed supernatural beings within near, making them flee for 5 rounds; weak targets that fail badly may be destroyed.",
    tags: ["control", "ward"],
  }),
  derivedPower({
    id: "post-mortem-data-extraction",
    name: "Post-Mortem Data Extraction",
    kind: "tech",
    derivedFromSpellId: "speak-with-dead",
    derivedFromSpellName: "Speak With Dead",
    tier: 3,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Interrogate residual data in a corpse, asking up to three yes-or-no questions.",
    tags: ["sensor", "communication"],
  }),
  derivedPower({
    id: "signal-jammer",
    name: "Signal Jammer",
    kind: "tech",
    derivedFromSpellId: "dispel-magic",
    derivedFromSpellName: "Dispel Magic",
    tier: 3,
    range: "Near",
    duration: "Instant",
    mechanics: "End one active power, spell, or signal affecting a visible target in range.",
    tags: ["utility", "counter"],
  }),
  derivedPower({
    id: "rapid-fabricator",
    name: "Rapid Fabricator",
    kind: "tech",
    derivedFromSpellId: "fabricate",
    derivedFromSpellName: "Fabricate",
    tier: 3,
    range: "Near",
    duration: "10 rounds",
    mechanics:
      "Reshape raw, nonliving materials up to tree-sized scale into a finished work that reverts when the duration ends.",
    tags: ["utility", "creation"],
  }),
  derivedPower({
    id: "thermal-detonator-burst",
    name: "Thermal Detonator Burst",
    kind: "tech",
    derivedFromSpellId: "fireball",
    derivedFromSpellName: "Fireball",
    tier: 3,
    range: "Far",
    duration: "Instant",
    damage: "4d6",
    mechanics:
      "Launch a compact thermal charge that detonates in a near-sized cube, damaging all creatures in the area.",
    tags: ["damage", "area", "munition"],
  }),
  derivedPower({
    id: "jetpack-boost",
    name: "Jetpack Boost",
    kind: "tech",
    derivedFromSpellId: "fly",
    derivedFromSpellName: "Fly",
    tier: 3,
    range: "Self",
    duration: "5 rounds",
    mechanics: "Fly near each round and hover in place for the duration.",
    tags: ["movement"],
  }),
  derivedPower({
    id: "vapor-phase-shift",
    name: "Vapor Phase Shift",
    kind: "tech",
    derivedFromSpellId: "gaseous-form",
    derivedFromSpellName: "Gaseous Form",
    tier: 3,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Phase yourself and carried gear into vapor, allowing flight through smoke-sized gaps while sensing nearby terrain and movement.",
    tags: ["transformation", "movement"],
  }),
  derivedPower({
    id: "holo-projection",
    name: "Holo-Projection",
    kind: "tech",
    derivedFromSpellId: "illusion",
    derivedFromSpellName: "Illusion",
    tier: 3,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Project a convincing visible and audible hologram filling up to a near-sized cube; inspection can reveal the projection.",
    tags: ["illusion", "utility", "hologram"],
  }),
  derivedPower({
    id: "arc-discharge",
    name: "Arc Discharge",
    kind: "tech",
    derivedFromSpellId: "lightning-bolt",
    derivedFromSpellName: "Lightning Bolt",
    tier: 3,
    range: "Far",
    duration: "Instant",
    damage: "3d6",
    mechanics:
      "Release a straight-line electrical discharge out to far range, damaging all creatures in its path.",
    tags: ["damage", "area", "energy"],
  }),
  derivedPower({
    id: "containment-field",
    name: "Containment Field",
    kind: "tech",
    derivedFromSpellId: "magic-circle",
    derivedFromSpellName: "Magic Circle",
    tier: 3,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Project a containment field against a named creature type; chosen creatures cannot attack or use hostile powers against those inside.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "energy-shield-matrix",
    name: "Energy Shield Matrix",
    kind: "tech",
    derivedFromSpellId: "protection-from-energy",
    derivedFromSpellName: "Protection From Energy",
    tier: 3,
    range: "Close",
    duration: "Focus",
    focus: true,
    mechanics:
      "Shield a touched creature from one energy type, making it immune to harm from that energy while maintained.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "encrypted-commlink",
    name: "Encrypted Commlink",
    kind: "tech",
    derivedFromSpellId: "sending",
    derivedFromSpellName: "Sending",
    tier: 3,
    range: "Unlimited",
    duration: "Instant",
    mechanics:
      "Send a brief encrypted message to a familiar creature on the same plane.",
    tags: ["communication", "tech"],
  }),
  derivedPower({
    id: "strategic-uplink",
    name: "Strategic Uplink",
    kind: "tech",
    derivedFromSpellId: "commune",
    derivedFromSpellName: "Commune",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Consult a strategic uplink and ask up to three yes-or-no questions answered truthfully.",
    tags: ["sensor", "divination"],
  }),
  derivedPower({
    id: "hydrokinesis-system",
    name: "Hydrokinesis System",
    kind: "tech",
    derivedFromSpellId: "control-water",
    derivedFromSpellName: "Control Water",
    tier: 4,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Move and shape a large section of water, making it change form, defy gravity, or flow differently.",
    tags: ["control", "utility"],
  }),
  derivedPower({
    id: "orbital-strike-beacon",
    name: "Orbital Strike Beacon",
    kind: "tech",
    derivedFromSpellId: "flame-strike",
    derivedFromSpellName: "Flame Strike",
    tier: 4,
    range: "Far",
    duration: "Instant",
    damage: "2d6",
    mechanics:
      "Mark one visible creature in range for a focused orbital or artillery strike.",
    tags: ["damage"],
  }),
  derivedPower({
    id: "molecular-freeze-ray",
    name: "Molecular Freeze Ray",
    kind: "tech",
    derivedFromSpellId: "pillar-of-salt",
    derivedFromSpellName: "Pillar of Salt",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Begin hardening a visible creature of LV 5 or less into a statue; three consecutive focused rounds make it permanent.",
    tags: ["control", "transformation"],
  }),
  derivedPower({
    id: "overload-strike",
    name: "Overload Strike",
    kind: "tech",
    derivedFromSpellId: "wrath",
    derivedFromSpellName: "Wrath",
    tier: 4,
    range: "Self",
    duration: "10 rounds",
    damage: "+1d8",
    mechanics:
      "Overload your weapons to become enhanced +2 and deal an additional d8 damage for the duration.",
    tags: ["weapon", "enhancement", "damage"],
  }),
  derivedPower({
    id: "recon-drone",
    name: "Recon Drone",
    kind: "tech",
    derivedFromSpellId: "arcane-eye",
    derivedFromSpellName: "Arcane Eye",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Deploy an invisible mobile drone you can see through; it sees in darkness, flies near each turn, and fits through tiny openings.",
    tags: ["sensor", "utility", "drone"],
  }),
  derivedPower({
    id: "toxic-gas-deployment",
    name: "Toxic Gas Deployment",
    kind: "tech",
    derivedFromSpellId: "cloudkill",
    derivedFromSpellName: "Cloudkill",
    tier: 4,
    range: "Far",
    duration: "5 rounds",
    damage: "2d6/round",
    mechanics:
      "Fill a near-sized cube with toxic gas that blinds and damages creatures at the start of their turns; weaker creatures that linger may die.",
    tags: ["damage", "area", "control"],
  }),
  derivedPower({
    id: "neural-scrambler",
    name: "Neural Scrambler",
    kind: "tech",
    derivedFromSpellId: "confusion",
    derivedFromSpellName: "Confusion",
    tier: 4,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Scramble one visible creature so it cannot act and moves randomly; powerful targets can shake it off with Wisdom.",
    tags: ["mental", "control"],
  }),
  derivedPower({
    id: "phase-gate",
    name: "Phase Gate",
    kind: "tech",
    derivedFromSpellId: "dimension-door",
    derivedFromSpellName: "Dimension Door",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Teleport yourself and one willing creature to any visible point.",
    tags: ["travel", "movement"],
  }),
  derivedPower({
    id: "predictive-algorithm",
    name: "Predictive Algorithm",
    kind: "tech",
    derivedFromSpellId: "divination",
    derivedFromSpellName: "Divination",
    tier: 4,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Run a predictive query and ask the GM one yes-or-no question answered truthfully.",
    tags: ["sensor", "divination"],
  }),
  derivedPower({
    id: "matter-phasing-tool",
    name: "Matter Phasing Tool",
    kind: "tech",
    derivedFromSpellId: "passwall",
    derivedFromSpellName: "Passwall",
    tier: 4,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Open a straight passage through a touched barrier, up to near distance in length.",
    tags: ["travel", "utility"],
  }),
  derivedPower({
    id: "bio-remodeling-suite",
    name: "Bio-Remodeling Suite",
    kind: "tech",
    derivedFromSpellId: "polymorph",
    derivedFromSpellName: "Polymorph",
    tier: 4,
    range: "Close",
    duration: "10 rounds",
    mechanics:
      "Transform a touched creature into a natural creature of equal or smaller size, with limits for unwilling targets.",
    tags: ["transformation", "control"],
  }),
  derivedPower({
    id: "energy-containment-sphere",
    name: "Energy Containment Sphere",
    kind: "tech",
    derivedFromSpellId: "resilient-sphere",
    derivedFromSpellName: "Resilient Sphere",
    tier: 4,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Project a weightless sphere around you that blocks passage and crushing force and can roll a near distance each turn.",
    tags: ["defense", "shield", "movement"],
  }),
  derivedPower({
    id: "reinforced-plating",
    name: "Reinforced Plating",
    kind: "tech",
    derivedFromSpellId: "stoneskin",
    derivedFromSpellName: "Stoneskin",
    tier: 4,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Harden your plating, raising AC to 17 for the duration, or 20 on a critical casting check.",
    tags: ["defense"],
  }),
  derivedPower({
    id: "grav-manipulator",
    name: "Grav Manipulator",
    kind: "tech",
    derivedFromSpellId: "telekinesis",
    derivedFromSpellName: "Telekinesis",
    tier: 4,
    range: "Far",
    duration: "Focus",
    focus: true,
    mechanics:
      "Lift and move a creature or object up to 1,000 pounds a near distance each round, or hold it in place.",
    tags: ["control", "repulsor"],
  }),
  derivedPower({
    id: "hardlight-wall",
    name: "Hardlight Wall",
    kind: "tech",
    derivedFromSpellId: "wall-of-force",
    derivedFromSpellName: "Wall of Force",
    tier: 4,
    range: "Near",
    duration: "5 rounds",
    mechanics:
      "Project a shaped, transparent hardlight wall over a near-sized area that blocks physical passage on the same plane.",
    tags: ["defense", "shield"],
  }),
  derivedPower({
    id: "targeted-extermination-protocol",
    name: "Targeted Extermination Protocol",
    kind: "tech",
    derivedFromSpellId: "divine-vengeance",
    derivedFromSpellName: "Divine Vengeance",
    tier: 5,
    range: "Self",
    duration: "10 rounds",
    mechanics:
      "Engage an extermination protocol: fly near, make weapons enhanced, and gain +4 to weapon attack and damage rolls.",
    tags: ["movement", "weapon", "enhancement"],
  }),
  derivedPower({
    id: "system-override",
    name: "System Override",
    kind: "tech",
    derivedFromSpellId: "dominion",
    derivedFromSpellName: "Dominion",
    tier: 5,
    range: "Near",
    duration: "10 rounds",
    mechanics:
      "Call powerful allied units with up to 16 combined levels to aid you for the duration.",
    tags: ["summoning", "control"],
  }),
  derivedPower({
    id: "execution-strike",
    name: "Execution Strike",
    kind: "tech",
    derivedFromSpellId: "judgment",
    derivedFromSpellName: "Judgment",
    tier: 5,
    range: "Close",
    duration: "5 rounds",
    mechanics:
      "Banish a touched intelligent creature of LV 10 or less for judgment, returning it altered by that judgment after the duration.",
    tags: ["control", "travel"],
  }),
  derivedPower({
    id: "dimensional-jump-drive",
    name: "Dimensional Jump Drive",
    kind: "tech",
    derivedFromSpellId: "plane-shift",
    derivedFromSpellName: "Plane Shift",
    tier: 5,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Transport yourself and willing creatures within close range to another plane, with uncertainty if the destination is unfamiliar.",
    tags: ["travel"],
  }),
  derivedPower({
    id: "future-simulation-engine",
    name: "Future Simulation Engine",
    kind: "tech",
    derivedFromSpellId: "prophecy",
    derivedFromSpellName: "Prophecy",
    tier: 5,
    range: "Self",
    duration: "Instant",
    mechanics:
      "Run a deep simulation and ask one question answered truthfully within the limits of available knowledge.",
    tags: ["sensor", "divination"],
  }),
  derivedPower({
    id: "energy-suppression-field",
    name: "Energy Suppression Field",
    kind: "tech",
    derivedFromSpellId: "antimagic-shell",
    derivedFromSpellName: "Antimagic Shell",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Create a near-sized suppression field centered on you where powers, spells, and magic items have no effect.",
    tags: ["defense", "counter"],
  }),
  derivedPower({
    id: "disintegration-beam",
    name: "Disintegration Beam",
    kind: "tech",
    derivedFromSpellId: "disintegrate",
    derivedFromSpellName: "Disintegrate",
    tier: 5,
    range: "Far",
    duration: "Instant",
    damage: "3d8",
    mechanics:
      "Fire a beam that reduces a creature or object to ash; weak creatures die outright, while stronger creatures take damage.",
    tags: ["damage", "energy"],
  }),
  derivedPower({
    id: "heavy-restraint-field",
    name: "Heavy Restraint Field",
    kind: "tech",
    derivedFromSpellId: "hold-monster",
    derivedFromSpellName: "Hold Monster",
    tier: 5,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Paralyze one visible creature; powerful targets can attempt a Strength check each turn to end the effect.",
    tags: ["control"],
  }),
  derivedPower({
    id: "neural-kill-command",
    name: "Neural Kill Command",
    kind: "tech",
    derivedFromSpellId: "power-word-kill",
    derivedFromSpellName: "Power Word Kill",
    tier: 5,
    range: "Near",
    duration: "Instant",
    mechanics:
      "Transmit a lethal command that kills one target of LV 9 or less that can receive it; failed casting is treated as a critical failure.",
    tags: ["mental", "damage"],
  }),
  derivedPower({
    id: "multi-phase-energy-orb",
    name: "Multi-Phase Energy Orb",
    kind: "tech",
    derivedFromSpellId: "prismatic-orb",
    derivedFromSpellName: "Prismatic Orb",
    tier: 5,
    range: "Far",
    duration: "Instant",
    damage: "3d8",
    mechanics:
      "Launch a concussive orb of chosen energy; targets anathema to that energy take double damage.",
    tags: ["damage", "energy"],
  }),
  derivedPower({
    id: "surveillance-feed",
    name: "Surveillance Feed",
    kind: "tech",
    derivedFromSpellId: "scrying",
    derivedFromSpellName: "Scrying",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "View and hear a distant creature or location on the same plane; observed creatures can notice the feed.",
    tags: ["sensor", "divination"],
  }),
  derivedPower({
    id: "advanced-morph-system",
    name: "Advanced Morph System",
    kind: "tech",
    derivedFromSpellId: "shapechange",
    derivedFromSpellName: "Shapechange",
    tier: 5,
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics:
      "Transform yourself and carried gear into a natural creature you have seen of LV 10 or less while retaining nonphysical stats.",
    tags: ["transformation"],
  }),
  derivedPower({
    id: "reinforcement-beacon",
    name: "Reinforcement Beacon",
    kind: "tech",
    derivedFromSpellId: "summon-extraplanar",
    derivedFromSpellName: "Summon Extraplanar",
    tier: 5,
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics:
      "Call in an elemental or outsider of LV 7 or less under your control; losing focus makes it hostile until returned.",
    tags: ["summoning", "control"],
  }),
  derivedPower({
    id: "long-range-teleport",
    name: "Long-Range Teleport",
    kind: "tech",
    derivedFromSpellId: "teleport",
    derivedFromSpellName: "Teleport",
    tier: 5,
    range: "Close",
    duration: "Instant",
    mechanics:
      "Teleport yourself and willing creatures within close range to a known same-plane destination, with off-target risk for unfamiliar locations.",
    tags: ["travel"],
  }),
];

const gmApprovalPowers: PowerSeed[] = [
  derivedPower({
    id: "force-trance",
    name: "Force Trance",
    kind: "force",
    derivedFromSpellId: "sleep",
    derivedFromSpellName: "Sleep",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Overwhelm weak minds and lull them into a brief trance.",
    tags: ["mental"],
  }),
  derivedPower({
    id: "sonic-stunner",
    name: "Sonic Stunner",
    kind: "tech",
    derivedFromSpellId: "sleep",
    derivedFromSpellName: "Sleep",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Emit a tuned pulse that can stun or drop vulnerable targets.",
    tags: ["sonic", "stun"],
  }),
  derivedPower({
    id: "social-override",
    name: "Social Override",
    kind: "tech",
    derivedFromSpellId: "charm-person",
    derivedFromSpellName: "Charm Person",
    approval: "gm-approval",
    range: "Near",
    duration: "Focus",
    focus: true,
    mechanics: "Use subliminal cues and slicing tricks to sway a humanoid target.",
    tags: ["influence", "slicing"],
  }),
  derivedPower({
    id: "force-barrier",
    name: "Force Barrier",
    kind: "force",
    derivedFromSpellId: "protection-from-evil",
    derivedFromSpellName: "Protection From Evil",
    approval: "gm-approval",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Create a ward against hostile supernatural or corrupted presences.",
    tags: ["defense", "ward"],
  }),
  derivedPower({
    id: "threat-dampener",
    name: "Threat Dampener",
    kind: "tech",
    derivedFromSpellId: "protection-from-evil",
    derivedFromSpellName: "Protection From Evil",
    approval: "gm-approval",
    range: "Self",
    duration: "Focus",
    focus: true,
    mechanics: "Tune a shield or jammer against a specific hostile signal or entity.",
    tags: ["defense", "shield"],
  }),
];

const excludedPowers: PowerSeed[] = [
  derivedPower({
    id: "excluded-cure-wounds",
    name: "Cure Wounds",
    kind: "force",
    derivedFromSpellId: "cure-wounds",
    derivedFromSpellName: "Cure Wounds",
    excluded: true,
    exclusionReason: "healing",
    mechanics: "Excluded because direct HP restoration is outside this ruleset.",
    tags: ["healing"],
  }),
];

export const forcePowers = [
  ...customStarWarsPowers,
  ...derivedForcePowers,
  ...derivedTechPowers,
  ...gmApprovalPowers,
  ...excludedPowers,
].map((power) => ({
  ...power,
  excluded: power.excluded ?? false,
  description:
    power.description ??
    `${power.name} ${
      power.source === "shadowdark-derived"
        ? `adapted from ${power.derivedFromSpellName}.`
        : "from the Star Wars Shadowdark homebrew powers list."
    }`,
  featureIds: power.featureIds ?? [],
})) satisfies ForcePower[];

function derivedPower(
  power: Omit<
    PowerSeed,
    "approval" | "availability" | "excluded" | "source" | "tier"
  > & {
    approval?: PowerSeed["approval"];
    excluded?: PowerSeed["excluded"];
    tier?: PowerSeed["tier"];
  },
): PowerSeed {
  return {
    ...power,
    source: "shadowdark-derived",
    availability: [power.kind],
    approval: power.approval ?? "allowed",
    excluded: power.excluded ?? false,
    tier: power.tier ?? 1,
  };
}
